disabled_rules:
- unused_setter_value
- trailing_whitespace
- function_body_length
- type_body_length
- function_parameter_count
opt_in_rules:
- force_unwrapping
- closure_body_length
- closure_spacing
- collection_alignment
- empty_collection_literal
- empty_string
- fallthrough
- file_name_no_space
- file_types_order
- identical_operands
- operator_usage_whitespace
- vertical_whitespace_opening_braces
- vertical_whitespace_closing_braces
- vertical_parameter_alignment_on_call
- vertical_parameter_alignment
- unused_import
- type_body_length

excluded:
- Pods
- MarketBroccoli/Application/AppDelegate.swift
- MarketBroccoli/Application/SceneDelegate.swift
- MarketBroccoli/Source/CustomUI/CustomCollectionViewFlowLayout.swift
- MarketBroccoli/Source/Home/HomeViewCells/HomeMDTableCell.swift
- MarketBroccoli/Source/Home/HomeViewCells/HomeOfferTableCell.swift
- MarketBroccoli/Source/Utils/Constant.swift
- MarketBroccoli/Source/Models
- MarketBroccoli/Source/Home/HomeViews/RecommendationView.swift
- TestGround
# Custom

force_cast: warning
force_try: warning
force_unwrapping: warning
identical_operands: error
file_length:
  warning: 500
  error: 1500
type_name:
  min_length: 2
  max_length: 40
identifier_name:
  min_length: 2
closure_body_length:
  warning: 50
