# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketBroccoli' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire','>= 5.0.4'
  pod 'Kingfisher','>= 5.13.2'
  pod 'SnapKit','>= 5.0.1'
  pod 'SwiftLint','>= 0.39.1'
  pod 'Then','>= 2.6.0'
  # Pods for MarketBroccoli

end
